build_and_store_wheels: &BUILD_AND_STORE_WHEELS
  install_cibuildwheel_script:
    - python -m pip install cibuildwheel==2.16.2
  run_cibuildwheel_script:
    - cibuildwheel
  wheels_artifacts:
    path: "wheelhouse/*"

env:
  VCPKG_INSTALLED_DIR: /tmp/vcpkg_installed

linux_aarch64_task:
  name: Build Linux aarch64 wheels.
  compute_engine_instance:
    image_project: cirrus-images
    image: family/docker-builder-arm64
    architecture: arm64
    platform: linux
    cpu: 2
    memory: 4G

  install_pre_requirements_script:
    - apt install -y python3-venv python-is-python3
  <<: *BUILD_AND_STORE_WHEELS

  matrix:
    - env:
        CIBW_BUILD: cp39-manylinux*
    # - env:
    #     CIBW_BUILD: cp310-manylinux*
    # - env:
    #     CIBW_BUILD: cp311-manylinux*
  env:
    CIBW_BUILD_FRONTEND: build
    CIBW_BUILD_VERBOSITY: 3
    CIBW_BEFORE_ALL_LINUX: |
      yum install -y zip flex bison gcc-gfortran
      echo "VCPKG_BINARY_SOURCES=$VCPKG_BINARY_SOURCES"
      echo "VCPKG_INSTALLED_DIR=$VCPKG_INSTALLED_DIR"
    CIBW_MANYLINUX_AARCH64_IMAGE: quay.io/pypa/manylinux_2_28_aarch64
    VCPKG_TARGET_TRIPLET: arm64-linux-dynamic-cxx17-abi1-rel
    CIBW_ENVIRONMENT_LINUX: >
      CMAKE_ARGS=-DBUILD_TESTING=OFF
      VCPKG_BINARY_SOURCES="clear;http,http://localhost:12321/\{name\}/\{version\}/\{sha\},readwrite"
      VCPKG_TARGET_TRIPLET=$VCPKG_TARGET_TRIPLET
      VCPKG_INSTALLED_DIR=$VCPKG_INSTALLED_DIR
      VCPKG_FORCE_SYSTEM_BINARIES=1
      LD_LIBRARY_PATH=$VCPKG_INSTALLED_DIR/$VCPKG_TARGET_TRIPLET/lib
    CIBW_REPAIR_WHEEL_COMMAND_LINUX: >
      auditwheel repair -w {dest_dir} {wheel} --exclude libarrow_python.so --exclude libarrow.so.1300
    CIBW_TEST_EXTRAS: test
    CIBW_TEST_COMMAND: py.test -s -vvv --pyargs arcae

# macos_arm64_task:
#   name: Build macOS arm64 wheels.
#   macos_instance:
#     image: ghcr.io/cirruslabs/macos-monterey-xcode

#   env:
#     PATH: /opt/homebrew/opt/python@3.10/bin:$PATH
#   install_pre_requirements_script:
#     - brew install python@3.10
#     - ln -s python3 /opt/homebrew/opt/python@3.10/bin/python
#   <<: *BUILD_AND_STORE_WHEELS