set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)

set(VCPKG_C_FLAGS "${VCPKG_C_FLAGS} -D_GLIBCXX_USE_CXX11_ABI=0 --std=c++17")
set(VCPKG_CXX_FLAGS "${VCPKG_CXX_FLAGS} -D_GLIBCXX_USE_CXX11_ABI=0 --std=c++17")

set(VCPKG_CMAKE_SYSTEM_NAME Linux)
#set(VCPKG_BUILD_TYPE Release)
